### ISSUE TITLE
AttributeError: 'module' object has no attribute 'wintypes'

### ISSUE THREAD

**Issue by freddiebarrsmith** [fireeye/flare-qdb#19]
https://freddiebarrsmith.com/flare.jpg

This error occurs

**Comment by freddiebarrsmith** [comment]
turns out you specifically have to alter the __init__ python script in order to add import ctypes.wintypes on windows systems

**Comment by john197611** [comment]
i have the same issue you post on this, please tell me how to fix this, i'm newbie please explain in detail, it would be greatful

https://freddiebarrsmith.com/flare.jpg

My error on windows 7, window 10 64bit :

C:\Users\win1\Desktop\1\test>dedosfuscator.exe
Traceback (most recent call last):
File "C:\Python27\Scripts\dedosfuscator-script.py", line 11, in
load_entry_point('flareqdb==1.0.6', 'console_scripts', 'dedosfuscator')()
File "C:\Python27\lib\site-packages\pkg_resources_init_.py", line 487, in l
oad_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "C:\Python27\lib\site-packages\pkg_resources_init_.py", line 2728, in
load_entry_point
return ep.load()
File "C:\Python27\lib\site-packages\pkg_resources_init_.py", line 2346, in
load
return self.resolve()
File "C:\Python27\lib\site-packages\pkg_resources_init_.py", line 2352, in
resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb_init_
.py", line 46, in
class SYMBOL_INFO(ctypes.Structure):
File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb_init_
.py", line 48, in SYMBOL_INFO
('SizeOfStruct', ctypes.wintypes.DWORD), # 1104
AttributeError: 'module' object has no attribute 'wintypes'

**Comment by freddiebarrsmith** [comment]
Add the line import ctypes.intypes at top of the flareqbd_init.py script

**Comment by john197611** [comment]
thank you so much for your help, i can run the dedosfuscator now and it's got this error, please tell me how to fix this error. Thank you so much :

INFO:root:>>>cmd: 2.bat
INFO:root:>>>cmd: /
INFO:root:>>>cmd: echo off
INFO:root:>>>cmd: 3/
INFO:root:>>>cmd: ,
INFO:root:>>>cmd: if6
INFO:root:<class 'struct.error'>: unpack requires a string argument of length 8
INFO:root:Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb\scripts\deDOSfuscator.py", line 96, in dump_cmd_64b
    cmdobj = q.readstruct(CmdObj, 'rdx')
  File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb\__init__.py", line 1016, in readstruct
    stru.vsParse(bytes)
  File "C:\Python27\lib\site-packages\vstruct\__init__.py", line 144, in vsParse
    offset = fobj.vsParse(sbytes, offset=offset)
  File "C:\Python27\lib\site-packages\vstruct\primitives.py", line 155, in vsParse
    self._vs_value = struct.unpack(self._vs_fmt, b)[0]
error: unpack requires a string argument of length 8

INFO:root:>>>cmd: +
INFO:root:>>>cmd: setlocal disableDelayedExpansion
INFO:root:>>>cmd: for %A in'chcp'
INFO:root:>>>cmd: /
INFO:root:>>>cmd: set "@chcp@=chcp  437>nul"
INFO:root:>>>cmd: 
INFO:root:>>>cmd: chcp 708 1 > nul
INFO:root:>>>cmd: set "@args@="
INFO:root:>>>cmd: set "@lo@= !#$&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~""
INFO:root:<type 'exceptions.UnicodeEncodeError'>: 'charmap' codec can't encode character u'\xa4' in position 20: character maps to <undefined>
INFO:root:Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb\scripts\deDOSfuscator.py", line 97, in dump_cmd_64b
    dump_cmdobj(q, cmdobj)
  File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb\scripts\deDOSfuscator.py", line 122, in dump_cmdobj
    print(output)
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xa4' in position 20: character maps to <undefined>

INFO:root:>>>cmd: 3
INFO:root:>>>cmd: /
INFO:root:>>>cmd: +
INFO:root:>>>cmd: setlocal enableDelayedExpansion
INFO:root:>>>cmd: for %N in0 1 93
