### ISSUE TITLE
readstruct

### ISSUE THREAD

**Issue by strictlymike** [fireeye/flare-qdb#3]
The QDB built-in `readstruct` can produce sporadic failures to parse structures because it determines its size based on page boundaries surrounding the address specified in `vexpr_va`:

```
    def readstruct(self, factory, vexpr_va, vexpr_size=0):
        stru = factory()
        base = self._vex(vexpr_va)
        size = self._vex(vexpr_size) if vexpr_size else ((base &
                                                          0xfffffffffffff000) +
                                                         0x1000 - base)
        bytes = self.readmem(base, 1, size, None)
        stru.vsParse(bytes)
        return stru
```

Depending on the resultant virtual address and the size of the particular `VStruct` instance, this can lead to errors like the following stack trace:

```
  File "\Samples\qcmd.py", line 35, in readstruct
    stru.vsParse(bytes)
  File "\Samples\qcmd.py", line 64, in vsParse
    offset = fobj.vsParse(sbytes, offset=offset)
  File "C:\Python27.amd64\lib\site-packages\vstruct\primitives.py", line 155, in
 vsParse
    self._vs_value = struct.unpack(self._vs_fmt, b)[0]
error: unpack requires a string argument of length 8
```

The solution is to instead use the `__len__` method of the `VStruct` instance to calculate the required buffer length to read from memory, as follows:

```
size = self._vex(vexpr_size) if vexpr_size else len(stru)
```

**Comment by john197611** [comment]
i can run the dedosfuscator now and it's got this error, please tell me how to fix this error. Thank you so much :

INFO:root:>>>cmd: 2.bat
INFO:root:>>>cmd: /
INFO:root:>>>cmd: echo off
INFO:root:>>>cmd: 3/
INFO:root:>>>cmd: ,
INFO:root:>>>cmd: if6
INFO:root:<class 'struct.error'>: unpack requires a string argument of length 8
INFO:root:Traceback (most recent call last):
File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb\scripts\deDOSfuscator.py", line 96, in dump_cmd_64b
cmdobj = q.readstruct(CmdObj, 'rdx')
File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb_init_.py", line 1016, in readstruct
stru.vsParse(bytes)
File "C:\Python27\lib\site-packages\vstruct_init_.py", line 144, in vsParse
offset = fobj.vsParse(sbytes, offset=offset)
File "C:\Python27\lib\site-packages\vstruct\primitives.py", line 155, in vsParse
self._vs_value = struct.unpack(self._vs_fmt, b)[0]
error: unpack requires a string argument of length 8

INFO:root:>>>cmd: +
INFO:root:>>>cmd: setlocal disableDelayedExpansion
INFO:root:>>>cmd: for %A in'chcp'
INFO:root:>>>cmd: /
INFO:root:>>>cmd: set "@CHCP@=chcp 437>nul"
INFO:root:>>>cmd:
INFO:root:>>>cmd: chcp 708 1 > nul
INFO:root:>>>cmd: set "@Args@="
INFO:root:>>>cmd: set "@lo@= !#$&'()*+,-./0123456789:;<=>?@abcdefghijklmnopqrstuvwxyz[]^_`abcdefghijklmnopqrstuvwxyz{|}~""
INFO:root:<type 'exceptions.UnicodeEncodeError'>: 'charmap' codec can't encode character u'\xa4' in position 20: character maps to
INFO:root:Traceback (most recent call last):
File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb\scripts\deDOSfuscator.py", line 97, in dump_cmd_64b
dump_cmdobj(q, cmdobj)
File "C:\Python27\lib\site-packages\flareqdb-1.0.6-py2.7.egg\flareqdb\scripts\deDOSfuscator.py", line 122, in dump_cmdobj
print(output)
File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\xa4' in position 20: character maps to

INFO:root:>>>cmd: 3
INFO:root:>>>cmd: /
INFO:root:>>>cmd: +
INFO:root:>>>cmd: setlocal enableDelayedExpansion
INFO:root:>>>cmd: for %N in0 1 93
